import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import Script from "next/script";
import { TelegramGlobal } from '@/shared/declare/telegram-global';
import { TonConnectProvider } from '@/shared/providers/ton-connect-provider';
import { Toasts } from '@/components/layout/toasts/toasts';

import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>
        <TonConnectProvider>
          <div className="container mx-auto h-[calc(100vh)] pb-[168px] overflow-y-auto">
            {children}
            <TelegramGlobal/>
          </div>
          <Toasts />
        </TonConnectProvider>
      </body>
      <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="afterInteractive"
        />
    </html>
  );
}
